name: appmetrica_flutter_sdk
description: A new flutter plugin project.
version: 0.0.1
repository: https://github.com/Malivix/appmetrica-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.lionid.appmetrica_flutter.appmetrica_flutter_sdk
        pluginClass: AppmetricaFlutterSdkPlugin
      ios:
        pluginClass: AppmetricaFlutterSdkPlugin
